spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
